[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# using thj dev address
evm_version = "shanghai"

fs_permissions = [{ access = "read-write", path = "./script/config.json" }]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
bArtio = "https://bartio.rpc.berachain.com/"

[etherscan]
bArtio = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/80084/etherscan", chain = 80084 }