[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

evm_version = "shanghai"

solc = "0.8.23"

fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[rpc_endpoints]
bArtio = "https://bartio.rpc.berachain.com/"

[etherscan]
bArtio = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/80084/etherscan", chain = 80084 }