[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

auto_detect_solc = false
solc = "0.8.26"
evm_version = "cancun"

fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@=src/"
]

[rpc_endpoints]
bArtio = "https://bartio.rpc.berachain.com/"
bera = "https://billowing-flashy-leaf.furtim-network.quiknode.pro/2c0dc24524597bb9aba3345ac1c275dad5dafc39/"

[etherscan]
bArtio = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/80084/etherscan", chain = 80084 }
bera = { key = "verifyContract", chain = 80094, url = "https://api.routescan.io/v2/network/mainnet/evm/80094/etherscan" }